/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.telas;

import biblioteca.classes.Estante;
import biblioteca.classes.Livro;
import javax.swing.JOptionPane;

/**
 *
 * @author jplim
 */
public class FuncAdicionarLivroEstante extends javax.swing.JFrame {
    Estante estante;
    FuncEscolherEstanteA func;
    
    public FuncAdicionarLivroEstante() {
        initComponents();
    }
    
    /*Inicia os componentes da tela e conecta as variaveis locais com as referencias
    uma variavel e a estante e a outra e referencia a tela anterior a essa para poder
    atualizar sua tabela mais facilmente*/
    
    public FuncAdicionarLivroEstante(Estante estante,FuncEscolherEstanteA func) {
        initComponents();
        this.estante=estante;
        this.func=func;
        lbIdEst.setText("Estante:" + estante.getIdentificacao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LNomeLivro = new javax.swing.JLabel();
        LDataPubLivro = new javax.swing.JLabel();
        LQuantPagLivro = new javax.swing.JLabel();
        LGeneroLivro = new javax.swing.JLabel();
        TfNomeLivro = new javax.swing.JTextField();
        TfDataPubLivro = new javax.swing.JTextField();
        TfQuantPagLivro = new javax.swing.JTextField();
        TfGeneroLivro = new javax.swing.JTextField();
        btConfAdcLivEst = new javax.swing.JButton();
        btCancAdcLivEst = new javax.swing.JButton();
        lbIdEst = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Livro na Estante");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/library.png")).getImage());

        jPanel1.setLayout(new java.awt.BorderLayout());

        LNomeLivro.setText("Nome:");

        LDataPubLivro.setText("Data de publicacão:");

        LQuantPagLivro.setText("Quantidade de paginas:");

        LGeneroLivro.setText("Genero");

        btConfAdcLivEst.setText("Confirmar");
        btConfAdcLivEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfAdcLivEstActionPerformed(evt);
            }
        });

        btCancAdcLivEst.setText("Cancelar");
        btCancAdcLivEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancAdcLivEstActionPerformed(evt);
            }
        });

        lbIdEst.setText("\"\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LQuantPagLivro)
                                .addGap(6, 6, 6)
                                .addComponent(TfQuantPagLivro)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LGeneroLivro)
                                .addGap(93, 93, 93)
                                .addComponent(TfGeneroLivro)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LNomeLivro)
                                        .addGap(95, 95, 95)
                                        .addComponent(TfNomeLivro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LDataPubLivro)
                                        .addGap(27, 27, 27)
                                        .addComponent(TfDataPubLivro)))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btConfAdcLivEst)
                                .addGap(41, 41, 41)
                                .addComponent(btCancAdcLivEst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lbIdEst)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIdEst)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LNomeLivro))
                    .addComponent(TfNomeLivro))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LDataPubLivro))
                    .addComponent(TfDataPubLivro))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LQuantPagLivro))
                    .addComponent(TfQuantPagLivro))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LGeneroLivro))
                    .addComponent(TfGeneroLivro))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfAdcLivEst)
                    .addComponent(btCancAdcLivEst))
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /*Fecha a tela*/
    private void btCancAdcLivEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancAdcLivEstActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancAdcLivEstActionPerformed
    
    /*Pega os valores escritos nos campos de texto e se forem validos cria um novo livro e
    adiciona na estante*/
    
    private void btConfAdcLivEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfAdcLivEstActionPerformed
        String nome = TfNomeLivro.getText();
        String DataPub = TfDataPubLivro.getText();
        String genero = TfGeneroLivro.getText();
        int qtdpag;
        try{
           qtdpag = Integer.parseInt(TfQuantPagLivro.getText());
        }catch (NumberFormatException e){
            qtdpag=-1;
        }
        
        if (!nome.equals("") && !DataPub.equals("") && !genero.equals("") && qtdpag > 0){
            Livro livro1 = new Livro(nome,DataPub,genero,qtdpag);
            estante.adicionarLivro(livro1);
            JOptionPane.showMessageDialog (null,"Livro foi adicionado a estante");
            func.carregarTabela();
            TfNomeLivro.setText("");
            TfDataPubLivro.setText("");
            TfGeneroLivro.setText("");
            TfQuantPagLivro.setText("");
        }else{
            JOptionPane.showMessageDialog (null,"valor(es) invalido(s)");
            TfNomeLivro.setText("");
            TfDataPubLivro.setText("");
            TfGeneroLivro.setText("");
            TfQuantPagLivro.setText("");
        }
    }//GEN-LAST:event_btConfAdcLivEstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncAdicionarLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncAdicionarLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncAdicionarLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncAdicionarLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncAdicionarLivroEstante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LDataPubLivro;
    private javax.swing.JLabel LGeneroLivro;
    private javax.swing.JLabel LNomeLivro;
    private javax.swing.JLabel LQuantPagLivro;
    private javax.swing.JTextField TfDataPubLivro;
    private javax.swing.JTextField TfGeneroLivro;
    private javax.swing.JTextField TfNomeLivro;
    private javax.swing.JTextField TfQuantPagLivro;
    private javax.swing.JButton btCancAdcLivEst;
    private javax.swing.JButton btConfAdcLivEst;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIdEst;
    // End of variables declaration//GEN-END:variables
}
