/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.telas;

import biblioteca.classes.Estante;
import biblioteca.classes.Livro;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jplim
 */
public class FuncRemoverLivroEstante extends javax.swing.JFrame {
    Estante estante;
    FuncEscolherEstanteR func;
    ArrayList<Livro> livros;
    
    public FuncRemoverLivroEstante() {
        initComponents();
    }
    
    /*Inicia os componentes da tela e conecta a variavel da tela com a referencia da estante 
    e da tela anterior dadas ao iniciar a tela */
    
    public FuncRemoverLivroEstante(Estante estante,FuncEscolherEstanteR func) {
        initComponents();
        this.estante=estante;
        this.func=func;
        livros = estante.getEstante();
        carregarTabela();
    }
    
    /*Carrega ou atualiza a tabela de livros*/
    
    public void carregarTabela(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome","Data de Publicação","Genero","Quantidade de Paginas"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}};
        
        for (int i=0;i < livros.size();i++){
            Object linha[] = {livros.get(i).getNome(),livros.get(i).getDataDePublicacao(),livros.get(i).getGenero(),livros.get(i).getQtDePaginas()};
            modelo.addRow(linha);
        }
        tblRemLiv.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btConfRemLivEst = new javax.swing.JButton();
        btCancRemLivEst = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRemLiv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover Livro da Estante");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/library.png")).getImage());

        btConfRemLivEst.setText("Confirmar");
        btConfRemLivEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfRemLivEstActionPerformed(evt);
            }
        });

        btCancRemLivEst.setText("Cancelar");
        btCancRemLivEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancRemLivEstActionPerformed(evt);
            }
        });

        tblRemLiv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Publicação", "Quantidade de Paginas", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRemLiv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btConfRemLivEst)
                .addGap(34, 34, 34)
                .addComponent(btCancRemLivEst)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfRemLivEst)
                    .addComponent(btCancRemLivEst))
                .addGap(67, 67, 67))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*Fecha a tela */
    private void btCancRemLivEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancRemLivEstActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancRemLivEstActionPerformed
    
    /*Remove o livro selecionado na tabela ao aperta o botão para confirmar e 
    atualiza a tabela*/
    
    private void btConfRemLivEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfRemLivEstActionPerformed
        int ind = tblRemLiv.getSelectedRow();
        if (ind >=0 && ind < livros.size()){
            livros.remove(ind);
            estante.setEstante(livros);
            func.carregarTabela();
            carregarTabela();
        }
    }//GEN-LAST:event_btConfRemLivEstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncRemoverLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncRemoverLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncRemoverLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncRemoverLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncRemoverLivroEstante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancRemLivEst;
    private javax.swing.JButton btConfRemLivEst;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRemLiv;
    // End of variables declaration//GEN-END:variables
}
