/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.telas;

import biblioteca.classes.Cliente;
import biblioteca.classes.Estante;
import biblioteca.classes.Livro;
import biblioteca.classes.Pedido;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jplim
 */
public class FuncEscolherLivPed extends javax.swing.JFrame {
    Cliente cliente;
    ArrayList<Livro> livros;
    ArrayList<Livro> livrosped;
    ArrayList<Integer> inds = new ArrayList<>();
    FuncFazerPedido ped;
    
    public FuncEscolherLivPed() {
        initComponents();
    }
    
    public FuncEscolherLivPed(Cliente cliente,Estante estante,ArrayList<Livro> livrosped,FuncFazerPedido ped) {
        initComponents();
        lbEst.setText(estante.getIdentificacao());
        this.cliente=cliente;
        this.livros=estante.getEstante();
        this.livrosped=livrosped;
        this.ped=ped;
        this.carregarTabela();
    }
    
     public void carregarTabela(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome","Data de Publicação","Genero","Quantidade de Paginas"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}};
        inds.clear();
        for (int i=0;i < livros.size();i++){
            if (!livros.get(i).isEmprestado()){
                Object linha[] = {livros.get(i).getNome(),livros.get(i).getDataDePublicacao(),livros.get(i).getGenero(),livros.get(i).getQtDePaginas()};
                modelo.addRow(linha);
                inds.add(livros.indexOf(livros.get(i)));
            }   
        }
        tblAdcPed.setModel(modelo);
     }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdcPed = new javax.swing.JTable();
        btnAdcP = new javax.swing.JButton();
        btnRemP = new javax.swing.JButton();
        lbEst = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fazer Pedido");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/library.png")).getImage());

        tblAdcPed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAdcPed);

        btnAdcP.setText("Adicionar no pedido");
        btnAdcP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcPActionPerformed(evt);
            }
        });

        btnRemP.setText("Remover do pedido");
        btnRemP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemPActionPerformed(evt);
            }
        });

        lbEst.setText("\"\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnAdcP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemP)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(lbEst)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbEst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdcP)
                    .addComponent(btnRemP))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    //coloca livro selecionado na lista de livros desejados para se pedir
    
    private void btnAdcPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcPActionPerformed
        int ind = tblAdcPed.getSelectedRow();
        if (ind >=0 && ind < livros.size()){
            livrosped.add(livros.get(inds.get(ind)));
            ped.carregarTabela2();
            this.carregarTabela();
        }
    }//GEN-LAST:event_btnAdcPActionPerformed

    private void btnRemPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemPActionPerformed
        int ind = tblAdcPed.getSelectedRow();
        if (ind >=0 && ind < livros.size()){
            livrosped.remove(livros.get(inds.get(ind)));
            ped.carregarTabela2();
            this.carregarTabela();
        }
    }//GEN-LAST:event_btnRemPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncEscolherLivPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncEscolherLivPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncEscolherLivPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncEscolherLivPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncEscolherLivPed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdcP;
    private javax.swing.JButton btnRemP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEst;
    private javax.swing.JTable tblAdcPed;
    // End of variables declaration//GEN-END:variables
}
