/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.telas;

import biblioteca.classes.Estante;
import biblioteca.classes.Livro;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jplim
 */
public class FuncEscolherEstanteR extends javax.swing.JFrame {
    ArrayList<Estante> estantes = new ArrayList<>();
  
    public FuncEscolherEstanteR() {
        initComponents();
        carregarTabela();
    }
    
    /*Inicia os componentes da tela ,conectas as variaveis com os argumentos dados 
    e carrega a tabela de estantes para o usuario poder selecionar alguma para remover
    um livro*/
    
    public FuncEscolherEstanteR(ArrayList<Estante> estantes) {
        initComponents();
        this.estantes=estantes;
        carregarTabela();
    }
    
    /*Carrega ou atualiza a tabela de estantes*/
    
    public void carregarTabela(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Identificacao","Localizacao","Genero","Quantidade de Livros"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        
        for (int i=0;i < estantes.size();i++){
            Object linha[] = {estantes.get(i).getIdentificacao(),estantes.get(i).getLocalizacao(),estantes.get(i).getGenero(),estantes.get(i).getQtLivrosEstante()};
            modelo.addRow(linha);
        }
        tblEscEst.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btConfEscEstR = new javax.swing.JButton();
        btCancEscEstR = new javax.swing.JButton();
        scrpanelEscEst = new javax.swing.JScrollPane();
        tblEscEst = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Escolher Estante");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/library.png")).getImage());

        btConfEscEstR.setText("Confirmar");
        btConfEscEstR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfEscEstRActionPerformed(evt);
            }
        });

        btCancEscEstR.setText("Cancelar");
        btCancEscEstR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancEscEstRActionPerformed(evt);
            }
        });

        tblEscEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Identificação", "Genero", "Localização", "Quantidade de livros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrpanelEscEst.setViewportView(tblEscEst);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btConfEscEstR)
                .addGap(39, 39, 39)
                .addComponent(btCancEscEstR)
                .addContainerGap(105, Short.MAX_VALUE))
            .addComponent(scrpanelEscEst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpanelEscEst, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfEscEstR)
                    .addComponent(btCancEscEstR))
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /*Se alguma estante estiver selecionada abre a tela para remover um livro nessa estante*/
    
    private void btConfEscEstRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfEscEstRActionPerformed
        int ind = tblEscEst.getSelectedRow();
        if (ind >=0 && ind < estantes.size()){
            new FuncRemoverLivroEstante(estantes.get(ind),this).setVisible(true);
        }
    }//GEN-LAST:event_btConfEscEstRActionPerformed
    
    /*Fecha a tela */
    
    private void btCancEscEstRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancEscEstRActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancEscEstRActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncEscolherEstanteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncEscolherEstanteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncEscolherEstanteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncEscolherEstanteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncEscolherEstanteR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancEscEstR;
    private javax.swing.JButton btConfEscEstR;
    private javax.swing.JScrollPane scrpanelEscEst;
    private javax.swing.JTable tblEscEst;
    // End of variables declaration//GEN-END:variables
}
