/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.telas;

import biblioteca.classes.Estante;
import biblioteca.classes.GerenciarBiblioteca;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jplim
 */
public class FuncEditarEstante extends javax.swing.JFrame {
    ArrayList<Estante> estantes = new ArrayList<>();
    GerenciarBiblioteca sistema;
    public FuncEditarEstante() {
        initComponents();
        carregarTabela();
        
    }
    /*Inicia os componentes da tela e conecta as variaveis locais com as referencias e inicia o 
    carregamento da tabela*/
    public FuncEditarEstante(GerenciarBiblioteca sistema) {
        initComponents();
        this.estantes=sistema.getEstantes();
        this.sistema = sistema;
        carregarTabela();
        
    }
    
    /*Esse metodo carrega ou atualiza a tabela da tela caso necessario*/
    
    public void carregarTabela(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Identificacao","Localizacao","Genero","Quantidade de Livros"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}};
        
        for (int i=0;i < estantes.size();i++){
            Object linha[] = {estantes.get(i).getIdentificacao(),estantes.get(i).getLocalizacao(),estantes.get(i).getGenero(),estantes.get(i).getQtLivrosEstante()};
            modelo.addRow(linha);
        }
        tblEst.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfEdtId = new javax.swing.JTextField();
        tfEdtLoc = new javax.swing.JTextField();
        tfEdtGen = new javax.swing.JTextField();
        labEdtId = new javax.swing.JLabel();
        labEdtLoc = new javax.swing.JLabel();
        labEdtGen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEst = new javax.swing.JTable();
        btConfEdtEst = new javax.swing.JButton();
        btCancEdtEst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Estante");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/library.png")).getImage());

        labEdtId.setText("Identificação:");

        labEdtLoc.setText("Localização:");

        labEdtGen.setText("Genero:");

        tblEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Identificação", "Genero", "Localização", "Quantidade de livros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEst);

        btConfEdtEst.setText("Confirmar");
        btConfEdtEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfEdtEstActionPerformed(evt);
            }
        });

        btCancEdtEst.setText("Cancelar");
        btCancEdtEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancEdtEstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labEdtId)
                                            .addComponent(labEdtLoc))
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfEdtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfEdtId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labEdtGen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfEdtGen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btConfEdtEst)
                                .addGap(30, 30, 30)
                                .addComponent(btCancEdtEst)))
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEdtId)
                    .addComponent(tfEdtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEdtLoc)
                    .addComponent(tfEdtLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEdtGen)
                    .addComponent(tfEdtGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfEdtEst)
                    .addComponent(btCancEdtEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /*Pega os valores escritos nos campos de texto e se forem validos edita a estante
    selecionada ao apertar o botão*/
    
    private void btConfEdtEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfEdtEstActionPerformed
        int ind = tblEst.getSelectedRow();
        if (ind >=0 && ind < estantes.size()){
            String id = tfEdtId.getText();
            String local = tfEdtLoc.getText();
            String genero = tfEdtGen.getText();


            if (!id.equals("") && !local.equals("") && !genero.equals("")){
                estantes.get(ind).setIdentificacao(id);
                estantes.get(ind).setLocalizacao(local);
                estantes.get(ind).setGenero(genero);
                tfEdtId.setText("");
                tfEdtLoc.setText("");
                tfEdtGen.setText("");
            }else{
                JOptionPane.showMessageDialog (null,"valor(es) invalido(s)");
                tfEdtId.setText("");
                tfEdtLoc.setText("");
                tfEdtGen.setText("");
            }
            carregarTabela();
        }
    }//GEN-LAST:event_btConfEdtEstActionPerformed
    
    /*Fecha a tela*/
    private void btCancEdtEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancEdtEstActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancEdtEstActionPerformed
    
    /*Ao clickar para selecionar alguma estante na tabela , os dados da tabela
    aparecem nos campos de texto,ajudando a mostrar qual estante esta sendo atualizada*/
    
    private void tblEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstMouseClicked
        int ind = tblEst.getSelectedRow();
        if (ind >=0 && ind < estantes.size()){
            Estante estante1 = estantes.get(ind);
            tfEdtId.setText(estante1.getIdentificacao());
            tfEdtLoc.setText(estante1.getLocalizacao());
            tfEdtGen.setText(estante1.getGenero());
        }
    }//GEN-LAST:event_tblEstMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncEditarEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncEditarEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncEditarEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncEditarEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncEditarEstante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancEdtEst;
    private javax.swing.JButton btConfEdtEst;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labEdtGen;
    private javax.swing.JLabel labEdtId;
    private javax.swing.JLabel labEdtLoc;
    private javax.swing.JTable tblEst;
    private javax.swing.JTextField tfEdtGen;
    private javax.swing.JTextField tfEdtId;
    private javax.swing.JTextField tfEdtLoc;
    // End of variables declaration//GEN-END:variables
}
