/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.telas;


import biblioteca.classes.Autor;
import biblioteca.classes.Editora;
import biblioteca.classes.Estante;
import biblioteca.classes.Funcionario;
import biblioteca.classes.GerenciarBiblioteca;
import biblioteca.classes.Livro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class FuncAdicionarLivroEstante extends javax.swing.JFrame {
    Estante estante;
    FuncEscolherEstanteA func;
    Funcionario funcionarioA;
    ArrayList <Autor> autores;
    ArrayList <Editora> editoras;
    GerenciarBiblioteca sistema;
            
    public FuncAdicionarLivroEstante() {
        initComponents();
    }
    
    /*Inicia os componentes da tela e conecta as variaveis locais com as referencias
    uma variavel e a estante e a outra e referencia a tela anterior a essa para poder
    atualizar sua tabela mais facilmente*/
    
    public FuncAdicionarLivroEstante(Estante estante,FuncEscolherEstanteA func,GerenciarBiblioteca sistema) {
        initComponents();
        this.estante=estante;
        this.func=func;
        this.funcionarioA=func.funcionarioA;
        this.autores=sistema.getAutores();
        this.editoras=sistema.getEditoras();
        this.sistema = sistema;
        lbIdEst.setText("Estante:" + estante.getIdentificacao());
        carregarAutores();
        carregarEditoras();
    }
    
    public void carregarAutores(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome","Pais de Origem","Data de Nascimento","Quantidade de Livros"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
            
        
        for (int i=0;i < autores.size();i++){
            Object linha[] = {autores.get(i).getNome(),autores.get(i).getPaisOrigem(),autores.get(i).getDataDeNascimento(),autores.get(i).getQtdLivrosEscritos()};
            modelo.addRow(linha);
        }
        tblAut.setModel(modelo);
    }
    
    public void carregarEditoras(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome","Pais de Origem","Data de Criação","Quantidade de Livros"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
            
        
        for (int i=0;i < editoras.size();i++){
            Object linha[] = {editoras.get(i).getNome(),editoras.get(i).getPaisOrigem(),editoras.get(i).getDataCriacao(),editoras.get(i).getQtdLivrosPublicados()};
            modelo.addRow(linha);
        }
        tblEdit.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LNomeLivro = new javax.swing.JLabel();
        LDataPubLivro = new javax.swing.JLabel();
        LQuantPagLivro = new javax.swing.JLabel();
        LGeneroLivro = new javax.swing.JLabel();
        TfNomeLivro = new javax.swing.JTextField();
        TfDataPubLivro = new javax.swing.JTextField();
        TfQuantPagLivro = new javax.swing.JTextField();
        TfGeneroLivro = new javax.swing.JTextField();
        btCancAdcLivEst = new javax.swing.JButton();
        btConfAdcLivEst = new javax.swing.JButton();
        lbIdEst = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAut = new javax.swing.JTable();
        lbAutor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEdit = new javax.swing.JTable();
        lbEditora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/library.png")).getImage());

        jPanel1.setLayout(new java.awt.BorderLayout());

        LNomeLivro.setText("Nome:");

        LDataPubLivro.setText("Data de publicacão:");

        LQuantPagLivro.setText("Quantidade de paginas:");

        LGeneroLivro.setText("Genero");

        btCancAdcLivEst.setText("Cancelar");
        btCancAdcLivEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancAdcLivEstActionPerformed(evt);
            }
        });

        btConfAdcLivEst.setText("Confirmar");
        btConfAdcLivEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfAdcLivEstActionPerformed(evt);
            }
        });

        lbIdEst.setText("\"\"");

        tblAut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAut);

        lbAutor.setText("Autor");

        tblEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEdit);

        lbEditora.setText("Editora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btConfAdcLivEst)
                                .addGap(47, 47, 47)
                                .addComponent(btCancAdcLivEst))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LNomeLivro)
                                    .addGap(95, 95, 95)
                                    .addComponent(TfNomeLivro))
                                .addComponent(LDataPubLivro)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TfDataPubLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LQuantPagLivro)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TfQuantPagLivro))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LGeneroLivro)
                                            .addGap(93, 93, 93)
                                            .addComponent(TfGeneroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lbIdEst)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbEditora)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbAutor)
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIdEst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancAdcLivEst)
                    .addComponent(btConfAdcLivEst))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LNomeLivro))
                    .addComponent(TfNomeLivro))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LDataPubLivro))
                    .addComponent(TfDataPubLivro))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LQuantPagLivro))
                    .addComponent(TfQuantPagLivro))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LGeneroLivro))
                    .addComponent(TfGeneroLivro))
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAutor)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEditora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Fecha a tela*/
    
    private void btCancAdcLivEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancAdcLivEstActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancAdcLivEstActionPerformed

     /*Pega os valores escritos nos campos de texto e se forem validos cria um novo livro e
    adiciona na estante*/
    
    private void btConfAdcLivEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfAdcLivEstActionPerformed
        String nome = TfNomeLivro.getText();
        String DataPub = TfDataPubLivro.getText();
        String genero = TfGeneroLivro.getText();
        int qtdpag,ind,ind2;
        ind =tblAut.getSelectedRow();
        ind2=tblEdit.getSelectedRow();
        try{
           qtdpag = Integer.parseInt(TfQuantPagLivro.getText());
        }catch (NumberFormatException e){
            qtdpag=-1;
        }
        
        if (!nome.equals("") && !DataPub.equals("") && !genero.equals("") && qtdpag > 0 && ind >=0 && ind2 >=0){
            Livro livro = new Livro(nome, DataPub, genero, qtdpag,autores.get(ind),estante,editoras.get(ind2));
            autores.get(ind).escreveuLivro(livro);
            editoras.get(ind2).publicouLivro(livro);
            funcionarioA.adicionarLivro(livro, estante);
            sistema.addLivro(livro);
            JOptionPane.showMessageDialog (null,"Livro foi adicionado a estante");
            func.carregarTabela();
            TfNomeLivro.setText("");
            TfDataPubLivro.setText("");
            TfGeneroLivro.setText("");
            TfQuantPagLivro.setText("");
            carregarAutores();
            carregarEditoras();
        
        }
        else if(ind < 0 || ind2 < 0){
            JOptionPane.showMessageDialog (null,"Autor ou editora não selecionado");
        }
        else{
            JOptionPane.showMessageDialog (null,"valor(es) invalido(s)");
            TfNomeLivro.setText("");
            TfDataPubLivro.setText("");
            TfGeneroLivro.setText("");
            TfQuantPagLivro.setText("");
        }
    }//GEN-LAST:event_btConfAdcLivEstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncAdicionarLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncAdicionarLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncAdicionarLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncAdicionarLivroEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncAdicionarLivroEstante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LDataPubLivro;
    private javax.swing.JLabel LGeneroLivro;
    private javax.swing.JLabel LNomeLivro;
    private javax.swing.JLabel LQuantPagLivro;
    private javax.swing.JTextField TfDataPubLivro;
    private javax.swing.JTextField TfGeneroLivro;
    private javax.swing.JTextField TfNomeLivro;
    private javax.swing.JTextField TfQuantPagLivro;
    private javax.swing.JButton btCancAdcLivEst;
    private javax.swing.JButton btConfAdcLivEst;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbIdEst;
    private javax.swing.JTable tblAut;
    private javax.swing.JTable tblEdit;
    // End of variables declaration//GEN-END:variables
}
