/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.telas;

import biblioteca.classes.Autor;
import biblioteca.classes.Editora;
import biblioteca.classes.Livro;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gusta
 */
public class InformacoesAutor extends javax.swing.JFrame {
    Autor autor;
    Editora editora;
    /**
     * Creates new form InformacoesAutor
     */
    public InformacoesAutor() {
        initComponents();
        carregarInfo();
        carregarInfor2();
    }

    public InformacoesAutor(Autor autor, Editora editora) {
        this.autor = autor;
        this.editora = editora;
        initComponents();
        carregarInfo();
        carregarInfor2();
    }

    public void carregarInfo(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Informações do autor"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        
        ArrayList<Livro> livros = autor.getLivros();
        ArrayList<Object> lista = new ArrayList<>();
        
        lista.add("Nome: "+ autor.getNome());
        lista.add("Data de nascimento: " + autor.getDataDeNascimento());
        lista.add("País de origem: " + autor.getPaisOrigem());
        lista.add("Livros publicados: " + autor.getLivros().size());
        for (int i = 0; i < lista.size(); i++) {
           Object linha0[] = {lista.get(i)};
           modelo.addRow(linha0);
        }
        
        for (int i=0;i < livros.size(); i++){
            Livro livro = livros.get(i);
            Object linha[] = {livro.getNome() + " - Estante: " + livro.getEstante().getIdentificacao()};
            modelo.addRow(linha);
             
        }
        jTable1.setModel(modelo);    }
    
    public void carregarInfor2(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Informações da editora"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        
        ArrayList<Livro> livros = editora.getLivros();
        ArrayList<Object> lista = new ArrayList<>();
        
        lista.add("Nome: " + editora.getNome());
        String expectedDate = editora.getDataCriacao().toZonedDateTime().format(DateTimeFormatter.ofPattern("d MMM uuuu"));
        lista.add("Fundada: " + expectedDate);
        lista.add("País: " + editora.getPaisOrigem());
        lista.add("Livros publicados: " + editora.getLivros().size());
        
        for (int i = 0; i < lista.size(); i++) {
           Object linha0[] = {lista.get(i)};
           modelo.addRow(linha0);
        }
        
        for (int i=0;i < livros.size(); i++){
            Livro livro = livros.get(i);
            Object linha[] = {livro.getNome() + " - Estante: " + livro.getEstante().getIdentificacao()};
            modelo.addRow(linha);
             
        }
        jTable2.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacoesAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacoesAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacoesAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacoesAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacoesAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
