/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.telas;

import biblioteca.classes.Autor;
import java.util.ArrayList;
import biblioteca.classes.Livro;
import biblioteca.classes.Estante;
import biblioteca.classes.GerenciarBiblioteca;
import biblioteca.classes.Pedido;
import java.net.URISyntaxException;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jp
 */
public class MostrarAcervo extends javax.swing.JFrame {
    ArrayList<Estante> estantes = new ArrayList<Estante>();
    ArrayList<Livro> todosLivros = new ArrayList<Livro>();
    GerenciarBiblioteca sistema;
    Pedido pedido;
    
    //Object[] linha;
    /**
     * Creates new form MostrarAcervo
     */
    public MostrarAcervo() {
        initComponents();
        carregarTabela();
    }
    public MostrarAcervo(ArrayList<Estante> estantes, GerenciarBiblioteca sistema){
        initComponents();
        this.estantes = estantes;
        carregarTabela();
        this.sistema = sistema;
        pedido = new Pedido(sistema.getCurrentCliente());
    }
    public void carregarTabela(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome","Data de Publicação","Genero","Quantidade de Páginas","Status","Estante"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        
        //Object linha[];
        System.out.println(1);
        for (int i=0;i < estantes.size();i++){
            ArrayList<Livro> estante = estantes.get(i).getEstante();
            for(int j=0;j < estante.size();j++) {
                todosLivros.add(estante.get(j));
                System.out.println(estante.get(j).getNome());
            }
        }
        for (int i=0;i < todosLivros.size();i++){
            Livro livro = todosLivros.get(i);
            Object linha[] = {livro.getNome(),livro.getDataDePublicacao(),livro.getGenero(),livro.getQtDePaginas(),(livro.isEmprestado()) ? "Não Disponível": "Disponivel", livro.getEstante().getIdentificacao()};
            modelo.addRow(linha);
             
        }
        jTable1.setModel(modelo);    }
    
    public void carregarTabela2(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome","Data de Publicação","Genero","Quantidade de Páginas","Status","Estante"},0){
            @Override
            public boolean isCellEditable(int row, int column){return false;}
        };
        
        //Object linha[];
        for (int i=0;i < pedido.getLivros().size(); i++){
            Livro livro = pedido.getLivros().get(i);
            Object linha[] = {livro.getNome(),livro.getDataDePublicacao(),livro.getGenero(),livro.getQtDePaginas(),(livro.isEmprestado()) ? "Não Disponível": "Disponivel", livro.getEstante().getIdentificacao()};
            modelo.addRow(linha);
             
        }
        jTable2.setModel(modelo);    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneAcervo = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPaneBolsa = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonFazerPedido = new javax.swing.JButton();
        jButtonAdicionarBolsa1 = new javax.swing.JButton();
        jButtonAutor1 = new javax.swing.JButton();
        jButtonOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/library.png")).getImage());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneAcervo.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneBolsa.setViewportView(jTable2);

        jButtonFazerPedido.setText("Fazer pedido");
        jButtonFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFazerPedidoActionPerformed(evt);
            }
        });

        jButtonAdicionarBolsa1.setText("Adicionar na bolsa");
        jButtonAdicionarBolsa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarBolsa1ActionPerformed(evt);
            }
        });

        jButtonAutor1.setText("Informações");
        jButtonAutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutor1ActionPerformed(evt);
            }
        });

        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneAcervo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
            .addComponent(jScrollPaneBolsa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonFazerPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jButtonAdicionarBolsa1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jButtonAutor1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jButtonOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(254, 254, 254))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPaneAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneBolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAutor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdicionarBolsa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFazerPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOrdenar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFazerPedidoActionPerformed
        pedido.setId(sistema.incrementIDPedido());
        pedido.efetuarPedido();
        try {
            sistema.saveData();
        } catch (URISyntaxException ex) {
            Logger.getLogger(MostrarAcervo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFazerPedidoActionPerformed

    private void jButtonAdicionarBolsa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarBolsa1ActionPerformed
        int index = jTable1.getSelectedRow();
        if (index >=0 && index < todosLivros.size()){
           Livro livroSelecionado = todosLivros.get(index);
           pedido.adicionarLivro(livroSelecionado);
           carregarTabela2();
        }
    }//GEN-LAST:event_jButtonAdicionarBolsa1ActionPerformed

    private void jButtonAutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutor1ActionPerformed
        int index = jTable1.getSelectedRow();
        Autor autor = todosLivros.get(index).getAutor();
        new InformacoesAutor(autor, todosLivros.get(index).getEditora()).setVisible(true);
    }//GEN-LAST:event_jButtonAutor1ActionPerformed

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        todosLivros.sort(Comparator.comparing(Livro::getGenero));
    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarAcervo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarBolsa1;
    private javax.swing.JButton jButtonAutor1;
    private javax.swing.JButton jButtonFazerPedido;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JScrollPane jScrollPaneAcervo;
    private javax.swing.JScrollPane jScrollPaneBolsa;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
